baseURL = 'https://birabittoh.github.io/'
languageCode = 'en-us'
title = 'BiRabittoh'
theme = 'archie'

#copyright = "© BiRabittoh"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
favicon = "favicon.ico"
paginate=3 # articles per page

[taxonomies]
   tag = "tags"
   #category = "categories"

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	#subtitle = "My blog and portfolio"
	#mathjax = true # enable MathJax support
	#katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/BiRabittoh"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/marco-andronaco/"

[[params.social]]
name = "E-Mail"
icon = "mail"
url = "mailto:andronacomarco@gmail.com"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Articles"
url = "/articles"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3